name: Publish to PyPI Registry

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Publish Python Package
      uses: mariamrf/py-package-publish-action@v1.0.0
      with:
        python_version: '3.9.16'
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
